name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_APP_NAME }}

jobs:
  dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - id: 'login'
      uses: google-github-actions/setup-gcloud@v1
    - id: 'auth-docker'
      run: gcloud auth configure-docker --quiet
    - id: 'build'
      run: docker build . -t $IMAGE_NAME
    - id: 'push'
      run: docker push $IMAGE_NAME
    - id: 'deploy'
      run: >
        gcloud run deploy ${{ vars.GCP_APP_NAME }}-dev 
        --update-env-vars="TELEGRAM_API_KEY_DEV=${{ secrets.TELEGRAM_API_KEY_DEV }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}, PORT=8081" 
        --image $IMAGE_NAME 
        --allow-unauthenticated 
        --region us-central1 
        --platform managed